"""Write Obsidian-compatible vault files."""

from pathlib import Path

from .compiler import Article
from .fetcher import VideoInfo


def _write_article(article: Article, vault_dir: Path) -> None:
    """Write a single article as an Obsidian-compatible markdown file."""
    filepath = vault_dir / f"{article.slug}.md"

    # Build frontmatter
    tags_str = "\n".join(f"  - {tag}" for tag in article.tags)
    sources_str = "\n".join(
        f"  - \"[{s['title']}](https://youtube.com/watch?v={s['video_id']})\""
        for s in article.source_videos
    )

    frontmatter = f"""---
title: "{article.title}"
tags:
{tags_str}
sources:
{sources_str}
---"""

    content = f"{frontmatter}\n\n{article.content}\n"
    filepath.write_text(content, encoding="utf-8")


def _write_index(articles: list[Article], vault_dir: Path) -> None:
    """Generate _index.md with all articles listed by topic."""
    lines = [
        "---",
        "title: Knowledge Base Index",
        "---",
        "",
        "# Knowledge Base Index",
        "",
        f"This vault contains **{len(articles)} articles** compiled from YouTube video transcripts.",
        "",
        "## Articles",
        "",
    ]

    for article in sorted(articles, key=lambda a: a.title):
        tags = ", ".join(f"`{t}`" for t in article.tags[:3])
        lines.append(f"- [[{article.title}]] {tags}")

    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("*Generated by [yt-to-knowledge](https://github.com/sarthakgoel31/yt-to-knowledge)*")
    lines.append("")

    filepath = vault_dir / "_index.md"
    filepath.write_text("\n".join(lines), encoding="utf-8")


def _write_sources(videos: list[VideoInfo], vault_dir: Path) -> None:
    """Generate _sources.md listing all videos processed."""
    lines = [
        "---",
        "title: Source Videos",
        "---",
        "",
        "# Source Videos",
        "",
        f"**{len(videos)} videos** were processed to build this knowledge base.",
        "",
        "| # | Title | Link |",
        "|---|-------|------|",
    ]

    for i, video in enumerate(videos, 1):
        url = f"https://youtube.com/watch?v={video.video_id}"
        # Escape pipe characters in titles
        safe_title = video.title.replace("|", "\\|")
        lines.append(f"| {i} | {safe_title} | [Watch]({url}) |")

    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("*Generated by [yt-to-knowledge](https://github.com/sarthakgoel31/yt-to-knowledge)*")
    lines.append("")

    filepath = vault_dir / "_sources.md"
    filepath.write_text("\n".join(lines), encoding="utf-8")


def write_vault(
    articles: list[Article],
    videos: list[VideoInfo],
    output_dir: Path,
) -> None:
    """Write the complete Obsidian vault to disk."""
    output_dir.mkdir(parents=True, exist_ok=True)

    print(f"Writing vault to {output_dir}/...")

    # Write each article
    for article in articles:
        _write_article(article, output_dir)

    # Write index and sources
    _write_index(articles, output_dir)
    _write_sources(videos, output_dir)

    print(f"Vault complete: {len(articles)} articles + index + sources")
    print(f"Open {output_dir}/ in Obsidian to explore the knowledge graph.")
